### PR TITLE
add chinese simple

### PR DESCRIPTION
**Pull request by a5161655**

### CODE REVIEW

**Comment by legobmw99** [comment]
Thank you.

**Comment by a5161655** [comment]
sorry I'm overlooked is a mistake,I just want to update a zh_cn.json file

**Comment by a5161655** [comment]
in version 1.16.1

**Comment by legobmw99** [comment]
I added it here: https://github.com/legobmw99/Wetstone/commit/529993826fc7c904e03ff60a6a15e792204b29a4

It seems github didn't pick up on that automatically

**Comment by a5161655** [comment]
okay,thank you

**Pull request closed without merging**
